I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script
    say "It’s always like this. The misleadingly calm night interrupted by reckless drivers, enjoying the lack of accountability that the dark affords them."
TypeError: say() missing 1 required positional argument: 'what'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script
    say "It’s always like this. The misleadingly calm night interrupted by reckless drivers, enjoying the lack of accountability that the dark affords them."
  File "C:\Users\taylo\OneDrive\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 2572, in execute
    Say.execute(self)
  File "C:\Users\taylo\OneDrive\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\taylo\OneDrive\Desktop\renpy-8.3.0-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
TypeError: say() missing 1 required positional argument: 'what'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
LoveBites 1.0
Mon Sep  2 11:03:37 2024
